title: '&2Toyz Token Shop'
prefix: '&a[&bMyTokens&a]&f'

#only one can be abled at one time
database:
  prefix: 'myt_'
  sqlite:
    use: true
    file: mytokens.db
  mysql:
    use: false
    host: 127.0.0.1
    database: mytokens
    port: 3306
    user: root
    password: password
    
settings:
  shop:
    #max is 6 if you use 1 only first 7 items will show
    rows: 1

  #sign shop
  sign-shop:
    #First line of the sign
    title: "[MyTokens]"

  #WIP but is working
  pvp:
    enablethrottle: false
    killthrottle: 3
    #Cooldown till you can kill that person again in seconds
    timeout: 30
  #Change certain command messages
  command-messages:
    console-give: "You got %amount Tokens!"
    console-take: "You had %amount Tokens taken from you!"
    cant-afford: "You do not have enough for this item!"
    thank-you: "You bought a item for %amount Tokens"

#Modes to drop Tokens
modes:
  #Player Vs Monster
  pve: false
  #Player vs Player
  pvp: false
  #When a user mines a block
  blockbreak: true

#Drop Item Config
dropitem: 
  drop: false
  #Alert to tell the user they got a token
  alert: "You just got a Token!"
  #Used Token Item Message
  used: "You got %amount tokens!"
  #Item to Drop
  item:
    #399 is "Nether Star"
    id: "399"
    name: Token
    #Delay to till user can pick up (In seconds)
    delay: 1
    lore: 
      - "You got Tokens!"
      - "Amount: %amount"
      - Right Click to claim your token

#Message to send to user
dropmsg:
  say: true
  #Messages to send in order
  messages:
    - "Hey, %player you got %amount tokens!"
    - "You now have %total tokens"
    
#Info item in Interface
infoitem:
  #368 is "Ender Perl"
  id: "368"
  #Only works on certain items (Doesn't work)
  glow: true
  name: My Tokens
  lore:
    - You have %total tokens
    
